version: "3.5"

services:
  ks-frontend:
    container_name: kanhasoft-frontend
    image: kanhasoft-frontend
    build: kanhasoft-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./kanhasoft-frontend:/usr/src/frontend/
    networks:
      - app-network

  ks-backend:
    container_name: kanhasoft-backend
    image: kanhasoft-backend
    build: kanhasoft-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./kanhasoft-backend:/usr/src/backend/
      - /usr/src/backend/node_modules
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    container_name: ks-postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanhasoft
      PG_DATA: /var/lib/postgresql/data
      # PGPORT: 5433
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend:
  backend:
  pgdata:
    # driver: local
